# This is a basic workflow to help you get started with Actions

name: Sample Book App Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-docker-image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
  deploy-dev:
    runs-on: self-hosted
    needs: [build-docker-image]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          environment: 'dev'
  api-integration-tests-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          environment: 'DEV'
  deploy-stg:
    runs-on: self-hosted
    needs: [api-integration-tests-dev]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          environment: 'stg'
  api-integration-tests-stg:
    runs-on: self-hosted
    needs: [deploy-stg]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          environment: 'STG'
  deploy-prd:
    runs-on: self-hosted
    needs: [api-integration-tests-stg]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          environment: 'prd'
  api-integration-tests-prd:
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          environment: 'PRD'