name: Sample Book App Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
  deploy-dev:
    runs-on: self-hosted
    needs: [build-docker-image]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with: 
          enviornment: 'dev'
      - name: Step description
        run: echo "Deployment triggered on DEV env..."
  api-integration-tests-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v3
      - name: Step description
        run: echo "API tests tirggered on DEV env..."
  deploy-stg:
    runs-on: self-hosted
    needs: [api-integration-tests-dev]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with: 
          enviornment: 'stg'
      - name: Step description
        run: echo "Deployment triggered on STG env..."
  api-integration-tests-stg:
    runs-on: self-hosted
    needs: [deploy-stg]
    steps:
      - uses: actions/checkout@v3
      - name: Step description
        run: echo "API tests tirggered on STG env..."
  deploy-prd:
    runs-on: self-hosted
    needs: [api-integration-tests-stg]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with: 
          enviornment: 'prd'
      - name: Step description
        run: echo "Deployment triggered on PRD env..."
  api-integration-tests-prd:
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
      - uses: actions/checkout@v3
      - name: Step description
        run: echo "API tests tirggered on PRD env..."
